server:
  port: 8091

#publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALPtoRvWEhXDXaF/eZ0niHhIyyrQ85n7o2rsh0JIUu90KvrBVECCRgIfsKWD2U69rEcoJX0kX9PDwRCLIy/XabsCAwEAAQ==
publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMC9HxSwFUW8jQdTjMJngZeKc0ivbR7fbvVvVqczOhFMDBxrD2qEArwz7bQDj4ruoejEgQBqoQGNOUMW+uI65zsCAwEAAQ==

spring:
  # database configuration
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
#      url: jdbc:mysql://localhost:3306/zqls
      url: jdbc:mysql://39.106.154.120:3306/zqls
      username: root
#      password: XvzyYd6lUV/ht2UqjGjXAUYJGIcWrBLVCLrJdx6jpfv2aQRtwMw6Ewv5HFtlAuq1C8/L6X6ZxmOs3ua997vMdw==
      password: bmm9Qmb659/MbIPSJ05TLkPpbu4U8s4QMXkZLf/egzIvAYs/+Y5rQuiLbBdrKGoA8oPj0GKqaAJNerdmOykWKg==
      filters: config,stat,wall
      connection-properties: config.decrypt=true;config.decrypt.key=${publickey}
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
  # 配置redis
  redis:
    host: 39.106.154.120
    port: 6379
    password: root
# dubbo configuration
dubbo:
  application:
    name: zqls-fms-service
  registry:
    address: zookeeper://39.106.154.120:2181
  protocol:
    name: dubbo
    port: 20882
  scan:
    base-packages: com.duanxin.zqls.*.service

# logging configuration
logging:
  level:
    com:
      duanxin:
        zqls:
          fms: debug

# mybatis configuration
mybatis:
  type-aliases-package: com.duanxin.zqls.fms.model
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


