# 服务端口
server:
  port: 9000

spring:
  # 邮件配置
  mail:
    host: smtp.163.com
    username: 18870735026@163.com
    password: 7l5SjDZS7IFTNmdrQV+57A==
    properties:
      mail:
        stmp:
          auth: true
          starttls:
            enable: true
            required: true
  # 消息中间件RabbitMQ配置
  rabbitmq:
    host: 39.106.154.120
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
  # 消费端
    listener:
      simple:
        concurrency: 5
        max-concurrency: 15
        acknowledge-mode: manual
        prefetch: 1

# 配置日志
logging:
  level:
    com:
      duanxin:
        zqls:
          ucenter: debug

# 配置dubbo
dubbo:
  application:
    name: zqls-mail-service
  registry:
    address: zookeeper://39.106.154.120:2181
  protocol:
    name: dubbo
    port: 20883
  scan:
    base-packages: com.duanxin.zqls.mail.service
