##################################
#            rabbitmq            #
##################################
spring:
  rabbitmq:
    addresses: 192.168.100.152:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

##################################
#            server              #
##################################
server:
  port: 8001
  servlet:
    context-path: /
