##################################
#            rabbitmq            #
##################################
# rabbitmq基本配置
spring:
  rabbitmq:
    addresses: 192.168.100.152:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    # 消费端配置
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        acknowledge-mode: manual    # 手动确认
        prefetch: 1   # 限流，表示消费端每次只消费1条消息

##################################
#            server              #
##################################
server:
  port: 8002
  servlet:
    context-path: /
