# 设置端口
server:
  port: 8070

# 配置阿里云短信服务
aliyun:
  sms:
    accessKeyId: LTAI4FkZJ7i8PzgzUpx54xrZ   #创建的accesskey中的AccessKey ID
    accessKeySecret: fZuwZ3iRjNRiNgaiIFSTnW1shJ67hS      #创建的accesskey中的Access Key Secret
    template_code: SMS_175571377      #模板管理中的模板CODE
    sign_name: 智取乐食       #签名管理中的签名

# 配置日志
logging:
  level:
    com:
      duanxin:
        zqls:
          ucenter: debug

# 配置dubbo
dubbo:
  protocol:
    name: dubbo   # 指定消费者端通信协议
    port: 20880
  registry:
    address: zookeeper://39.106.154.120:2181    # 指明注册中心zookeeper
  consumer:
    check: false    # 指定不进行检查服务提供者是否存在
    loadbalance: roundrobin   # 指定负载均衡算法（轮询算法）
    timeout: 3000   # 指定超时时间
  application:
    name: zqls-ucenter-web    # 指定当前工程名称
# 配置RabbitMQ
spring:
  rabbitmq:
    host: 39.106.154.120
    username: root
    password: root
  # 上传文件的限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

redisson:
  address: redis://39.106.154.120:6379